### ISSUE TITLE
Tabs and float action button position on app bar extended

### ISSUE THREAD

**Issue by mkhairi** [band-x-media/SASS-Material-Design-for-Bootstrap#8]
Hi, i experience this issue when using app-bar-extended class with tabs or float action button.
![tabs](https://cloud.githubusercontent.com/assets/7901659/8590274/ad94eac4-2651-11e5-9be3-349200df525a.png)

**Comment by andrew-waters** [comment]
Thanks for letting me know about this - I've created some new pages for [Example Layouts](http://code.band-x.media/SASS-Material-Design-for-Bootstrap/layout/examples/) that will have a few test layouts to see these a bit quicker than I'm currently able to.
