### ISSUE TITLE
Bower json relative main paths

### ISSUE THREAD

**Issue by ghost** [band-x-media/SASS-Material-Design-for-Bootstrap#9]
Hi,

i was including your project in my own project because i absolutely love the library.

I found one issue though including it in my build process via Gulp and using the main-bower-files component to pull it into my own CSS and JS files ignored your package because the main paths in your bower.json are relative to the root "/" by removing the trailing slash things worked.

Maybe you want to adjust that?

**Comment by andrew-waters** [comment]
Thanks for letting me know about this @mickske - I haven't used it as a foundation for any other builds (yet) - could you confirm this fixes your issue?

**Comment by ghost** [comment]
Thanks andrew that did it :+1:
